specs:
  paths:
    - 'specs/**/*.feature.md'
  format: 'markdown+yaml'

github:
  project_owner: 'ganesh47'
  project_number: 6
  project_name: 'Specs Board'
  status_field: 'Status'
  status_backlog: 'Todo'
  issue_labels:
    - 'spec'
    - 'feature'

codex:
  context_paths:
    - 'src'
    - 'tests'
